package com.cz.sample.custom.category;

import android.util.ArrayMap;

import androidx.annotation.NonNull;

import com.cz.android.sample.api.AndroidSampleConstant;
import com.cz.android.sample.api.CategoryGenerator;
import com.cz.android.sample.api.item.CategoryItem;
import com.cz.android.sample.api.item.RegisterItem;
import com.cz.android.sample.library.category.SampleCategoryGenerator;

import java.util.ArrayList;
import java.util.List;

/**
 * Generate category by its package name.
 **/
@CategoryGenerator
public class MyPackageCategoryGenerator implements SampleCategoryGenerator {

    @Override
    public List<CategoryItem> generate(@NonNull List<RegisterItem> registerItemList) {
        List<CategoryItem> categoryItemList=new ArrayList<>();
        if(null!=registerItemList){
            //Step1: Analysis of the package name from all the registered sample classes.
            String packageName=null;
            String lastClassName=null;
            for(RegisterItem registerItem:registerItemList){
                String className = registerItem.clazz.getName();
                if(null==lastClassName){
                    lastClassName=className;
                } else {
                    String commonPackage=getCommonPackage(className,lastClassName);
                    if(null==packageName||!packageName.equals(commonPackage)){
                        packageName=commonPackage;
                    }
                }
            }
            //Step2: generate all the categories by the class's package automatically
            ArrayMap<String,CategoryItem> packageCategoryList=new ArrayMap<>();
            for(RegisterItem registerItem:registerItemList){
                if(AndroidSampleConstant.CATEGORY_ROOT.equals(registerItem.category)){
                    //Use the default category that generated by the package.
                    String className = registerItem.clazz.getName();
                    String simpleName = registerItem.clazz.getSimpleName();
                    int end = className.lastIndexOf(simpleName);
                    String path = className.substring(packageName.length() + 1, end-1);
                    String[] pathArray = path.split("\\.");

                    String category=AndroidSampleConstant.CATEGORY_ROOT;
                    for(String str:pathArray){
                        CategoryItem categoryItem = packageCategoryList.get(str);
                        String title = capitalize(str);
                        if(null==categoryItem){
                            categoryItem=new CategoryItem(title,null,category);
                            packageCategoryList.put(str,categoryItem);
                            categoryItemList.add(categoryItem);
                        }
                        category=title;
                    }
                    registerItem.category=category;
                }
            }
        }
        return categoryItemList;
    }

    private String capitalize(String str) {
        if(str == null || str.isEmpty()) {
            return str;
        }
        return str.substring(0, 1).toUpperCase() + str.substring(1);
    }

    private String getCommonPackage(String className1,String className2){
        int i1=0,i2=0;
        String packageName=null;
        while(i1==i2){
            i1=className1.indexOf(".",i1+1);
            i2=className2.indexOf(".",i2+1);
            if(-1==i1||-1==i2){
                break;
            }
            if(className1.substring(0,i1).equals(className2.substring(0,i2))){
                //The two of the classes here have the same package.
                packageName=className1.substring(0,i1);
            }
        }
        return packageName;
    }
}
